name=Drv8835
version=0.0.1
author=Interested-In-Spresense
maintainer=Interested-In-Spresense
sentence= DRV8835 Motor Driver Library.
paragraph= DRV8835 Motor Driver Library.
category=Signal Input/Output
url=
architectures=all
